sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t krystyna/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true krystyna/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "new-docker-react"
  env: "Newdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-455445909749"
  bucket_path: "new-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
