language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t krystyna/docker-react -f Dockerfile.dev .


script:
  - docker run krystyna/docker-react npm run test -- --coverage
